language: php

php:
  - 5.6

before_install:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install --prefer-source --dev --no-interaction
 - mkdir -p build/logs

script:
 - php vendor/bin/phpunit --bootstrap test/bootstrap.php

after_script:
 - php vendor/bin/coveralls